### ISSUE TITLE
Getting unexpected keyword argument 'kind' when pulling signals.

### ISSUE THREAD

**Issue by rob-yerc** [amphoradata/python-sdk#20]
Just updated to sdk 0.10.21.  When executing this code snippet, I get the error with traceback below:
amphora = client.get_amphora("09914fde-b547-489c-a3f2-5a0682138051")
signals = amphora.get_signals()
fromdate=datetime.strptime('2020-05-20 00:00:00','%Y-%m-%d %H:%M:%S')
enddate=datetime.strptime('2020-10-12 23:59:59','%Y-%m-%d %H:%M:%S')
dt_range = DateTimeRange(_from=fromdate,to=enddate)
df = signals.pull(date_time_range=dt_range, include_wt=False, tsi_api="GetEvents").to_pandas() 

Traceback (most recent call last):
  File "signals_query.py", line 45, in <module>
    df = signals.pull(date_time_range=dt_range, include_wt=False, tsi_api="GetEvents").to_pandas()
  File "/home/rlrobert/epiic/fa01/.venv/lib64/python3.8/site-packages/amphora/amphora_signals.py", line 201, in pull
    variables = get_inline_variables(signals, include_wt)
  File "/home/rlrobert/epiic/fa01/.venv/lib64/python3.8/site-packages/amphora/amphora_signals.py", line 230, in get_inline_variables
    variable = api.NumericVariable(
TypeError: __init__() got an unexpected keyword argument 'kind'

Looking at the NumericVariable class in amphora_api_client/models/numeric_variable.py there is no 'kind' attribute.  If I comment out line 231 in amphora/amphora_signals.py, the error goes away and data is returned.

**Comment by xtellurian** [comment]
I looked into this issue, and it seems like the discriminator property was removed when I updated the TSI library to the GA version.

I should be able to fix in the next version.

**Comment by xtellurian** [comment]
This should be fixed in amphora-python v 0.10.25

**Comment by xtellurian** [comment]
This regressed in v0.10.27 when the swagger doc inheritence hierarchy was flattened.

The variables (numeric, aggregate) need the `kind` variable so they can be deserialised correctly.

**Comment by xtellurian** [comment]
@rob-yerc this issue should be resolved (again) in 0.10.29.dev1

`pip install amphoradata==0.10.29.dev1`

**Comment by rob-yerc** [comment]
Installed 0.10.29.dev1 and verified that this issue no longer occurs

**Comment by xtellurian** [comment]
I've promoted `0.10.29` as it seems stable
