### ISSUE TITLE
Return location when searching Amphora

### ISSUE THREAD

**Issue by xtellurian** [amphoradata/python-sdk#22]
Current status: the description and location (lat,lon) are not returned from the API when using the `/api/search-v2` endpoint.

Initial reasons was to minimise the size of results returned when searching. The descriptions can be quite large. Including descriptions in a long list could significantly increase time on the wire for data transfer.

**Comment by rob-yerc** [comment]
Understand the performance concerns.  The description is a nice to have as we are only using it to be able to provide additional information to the user when they are browsing a list of available datasets.  The labels and amphora name should be sufficient.  The lat,long are much more important.

**Comment by xtellurian** [comment]
Lat, Lon should be possible.

I'll scope it out and see how long it should take

**Comment by xtellurian** [comment]
@rob-yerc this is implemented in amphora python `0.10.27-dev1`

There are two numeric properties on each BasicAmphora model that is returned from the search endpoint.

**Comment by rob-yerc** [comment]
@xtellurian tested 0.10.27-dev1.  Worked great!

**Comment by xtellurian** [comment]
great! I'll promote that version and close this issue
