### ISSUE TITLE
issue importing 'SignalDto' from 'amphora_client'

### ISSUE THREAD

**Issue by maxmills1** [amphoradata/python-sdk#6]
received ImportError: cannot import name 'SignalDto' from 'amphora_client'

**Comment by maxmills1** [comment]
I upgraded to version 0.7.0.dev1 and received the error when running my program. What should I do?

**Comment by xtellurian** [comment]
#4

**Comment by xtellurian** [comment]
`SignalDto` has be renamed to `Signal`, along with other classes ending in DTO.

The change is backwards compatible (previous versions still work) but code needs to be refactored to move to >=0.7.0

@maxmills1 try replacing the import like so:

```py
from amphora_client import Signal
signal = Signal()
```
