### ISSUE TITLE
Error thrown during signal values serialisation

### ISSUE THREAD

**Issue by xtellurian** [amphoradata/python-sdk#8]
While trying to load data, running into the following error using the amphoradata==0.7.1.dev1

```
  File "/usr/local/lib/python3.7/site-packages/amphora_client/api/amphorae_api.py", line 1419, in amphorae_signals_upload_signal_batch
    return self.amphorae_signals_upload_signal_batch_with_http_info(id, request_body, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.7/site-packages/amphora_client/api/amphorae_api.py", line 1511, in amphorae_signals_upload_signal_batch_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.7/site-packages/amphora_client/api_client.py", line 342, in call_api
    _preload_content, _request_timeout, _host)
  File "/usr/local/lib/python3.7/site-packages/amphora_client/api_client.py", line 130, in __call_api
    path_params = self.sanitize_for_serialization(path_params)
  File "/usr/local/lib/python3.7/site-packages/amphora_client/api_client.py", line 231, in sanitize_for_serialization
    for key, val in six.iteritems(obj_dict)}
  File "/usr/local/lib/python3.7/site-packages/amphora_client/api_client.py", line 231, in <dictcomp>
    for key, val in six.iteritems(obj_dict)}
  File "/usr/local/lib/python3.7/site-packages/amphora_client/api_client.py", line 227, in sanitize_for_serialization
    for attr, _ in six.iteritems(obj.openapi_types)
AttributeError: 'builtin_function_or_method' object has no attribute 'openapi_types'
```

**Comment by xtellurian** [comment]
The problem may be caused by an 'invalid' python object as it is attempted to be serialised.

https://github.com/amphoradata/python-sdk/blob/master/generated/amphora_client/api_client.py#L191

**Comment by xtellurian** [comment]
The problem must be in the Python SDK itself. Because the error is thrown during serialisation, a call is never made to the API.

**Comment by xtellurian** [comment]
This error occurs when the objects that need to be serialized are not recognised by the open API serializer.

The code expects the object to be an `OpenAPI model`, and it trying to return the properties dict. But the object is not an OpenAPI model, and hence has no attribute 'openapi_types'.

Possible workarounds:
* make sure all objects to be serialised are one of: None, str, int, long, float, bool, datetime.datetime, datetime.date, list, dict, or OpenAPI model (i.e. the classes that come with the SDK).
* serialise the objects *before* passing into `amphorae_signals_upload_signal_batch`

**Comment by rob-yerc** [comment]
I added the following debug statement just before the actual call to the amphorae_signals_upload_signal_batch:

print("BEFORE CALL:",type([sensordata]),[sensordata])
newdata=amphora_api.amphorae_signals_upload_signal_batch(id, request_body = [sensordata])

Here is the output:
BEFORE CALL: <class 'list'> [{'t': datetime.datetime(2019, 8, 5, 16, 25, 5), 'sensortemperature': 63.7, 'depth': 1.072}]

I then added this debug statement on line 192 in api_client.py:

print(type(obj),"OBJ:",obj)

Here is the output after executing the amphorae_signals_upload_signal_batch call:

<class 'str'> OBJ: application/json
<class 'str'> OBJ: application/json
<class 'str'> OBJ: OpenAPI-Generator/0.7.1.dev1/python
<class 'dict'> OBJ: {'id': <built-in function id>}
<class 'builtin_function_or_method'> OBJ: <built-in function id>
Traceback (most recent call last):

**Comment by rob-yerc** [comment]
So for the second workaround-how do I serialise the object before passing it to the amphorae_signals_upload_signal_batch?

**Comment by xtellurian** [comment]
To serialise before passing to amphorae_signals_upload_signal_batch, try doing this:

```py
import json

serialisedSensorData = []
for sensorValues in [sensordata]:
    s = json.dumps(sensorValues)
    serialisedSensorData.append(s) # add the serialised values to an array
    print(s) # do a sanity check and look at the serialised data

amphorae_signals_upload_signal_batch(id, serialisedSensorData)
```

**Comment by xtellurian** [comment]
@rob-yerc what's the `builtin_function_or_method` class?

> <class 'builtin_function_or_method'> OBJ: 

I saw that in the error log, that might be the object that cannot be serialised.

**Comment by rob-yerc** [comment]
I was wondering the same thing but I don't  know what it is.  The object I am passing to the amphorae_signals_upload_signal_batch is a recognized as a list object the statement before the call.

I will try serialising the data.

**Comment by xtellurian** [comment]
Perhaps it's due to the use of the `list()` function.

https://docs.python.org/3.2/library/functions.html#list

**Comment by rob-yerc** [comment]
Found the issue.  The variable that I was using to store the amphora id was different than the one I was using in the call to amphorae_signals_upload_signal_batch.  As a result the variable id was not set and since id is a python builtin function that is what was being passed to the api call resulting in the strange debug message:

<class 'dict'> OBJ: {'id': }
<class 'builtin_function_or_method'> OBJ:

**Comment by xtellurian** [comment]
Thanks for sharing @rob-yerc, I'm going to close this issue.
